### ISSUE TITLE
Error in console

### ISSUE THREAD

**Issue by kaal-1** [ModdedMinecraft/MMCRestrict#1]
Minecraft 1.10.2
Latest SpongeForge (Forge 2281)

https://hastebin.com/itamebejis.bash

**Comment by leelawd** [comment]
Appears to be something with the scheduler for checking loaded chunks for banned blocks, Do you currently have anything set as world banned?

**Comment by kaal-1** [comment]
Yes, I have the mega, sacred, and enchanted sacred rubber saplings from MFR.
It's just these 3 items that are banned on the server.

**Comment by leelawd** [comment]
Could you try with the latest version and see if this still happens?

https://ore.spongepowered.org/leelawd93/MMCRestrict/versions/1.2.1

**Comment by leelawd** [comment]
Any update on whether this is still happening? would like to get this issue closed.

**Comment by kaal-1** [comment]
Apparently 1.2.1 fixes it. :) thank you
