### ISSUE TITLE
Data saved to file incorrectly

### ISSUE THREAD

**Issue by Valandur** [ModdedMinecraft/MMCRestrict#10]
https://github.com/ModdedMinecraft/MMCRestrict/blob/dc5eb02070ee6c2554d193bd76ace47a76e2d2ab/src/main/java/net/moddedminecraft/mmcrestrict/Data/ItemData.java#L40
https://github.com/ModdedMinecraft/MMCRestrict/blob/dc5eb02070ee6c2554d193bd76ace47a76e2d2ab/src/main/java/net/moddedminecraft/mmcrestrict/Data/ItemData.java#L41

I believe there is a copy-paste error on these few lines, leading restricted items not being saved to the config file correctly

**Comment by leelawd** [comment]
strange how i missed this... Thank you.
