### ISSUE TITLE
[Suggestion] Add permission nodes for individual items

### ISSUE THREAD

**Issue by DragaoNimhe** [ModdedMinecraft/MMCRestrict#14]
As stated in my title, I would like banned items to generate a permission node that allows players with that permission to bypass the ban. I want to be able to allow certain, trusted, people to be able to use a few of our banned items, but not all of them. Love the plugin, thanks so much for it!

**Comment by leelawd** [comment]
This is already implemented, i really should provide a better usage guide, this is kind of my fault not a lot of people know this exists lol

Simply give them a permission along the lines of this example:

Item: `minecraft:diamond_sword`
permission: `mmcrestrict.bypass.own.minecraft.diamond_sword`

Any : has to be replaced with a . in the permission node.

replace "own" with "use", "craft", "drop", "use", "place", "break" for the different individual nodes.
