### ISSUE TITLE
[Suggestion] Ability to add block-place limit to some blocks.

### ISSUE THREAD

**Issue by kobliznik** [ModdedMinecraft/MMCRestrict#19]
Hello there,

I want to ask if you could implement the function where you can specify blocks along with a place limit and players won't be able to place blocks over the limit.

For example if you set limit on ID minecraft:furnace to 10, nobody will be able to place more than 10 furnaces. World and Group options would be great too.

It fits to MMCRestrict theme.

Thanks, Trochu.

**Comment by Trochu** [comment]
Still no response?

**Comment by leelawd** [comment]
Apologies, Been busy with a lot of other things and RL has gotten in the way.
Iv had a few requests for this kind of feature and will be working on adding it hopefully alongside another rework

**Comment by d4julian** [comment]
> Still no response?

https://github.com/AuraDevelopmentTeam/AuraBlockLimit/releases/tag/v1.1.3

**Comment by leelawd** [comment]
Seeing as this is already in another plugin, it will be unlikely i will add this to this plugin.
