### ISSUE TITLE
[Suggestion] Adding the ability to restrict items in groups

### ISSUE THREAD

**Issue by Ichibruh** [ModdedMinecraft/MMCRestrict#22]
An example of this would be what I am trying to achieve currently. I have two groups, "Magic" and "Science", and I am restricting all magic items from those who are in group "Science", and all science items from those in group "Magic". Both creating restrictions specific to groups and/or replacing "ItemID =" in BannedItems.conf with the ability to select items under a mod.

ItemID would be simpler if it were in a permission format like " mmcrestrict.banitem.bloodmagic.* "
where * would select every item under BloodMagic.

**Comment by leelawd** [comment]
Interesting, Ill see what i can do about this

**Comment by Ichibruh** [comment]
Great! Thank you for your efforts :)

**Comment by leelawd** [comment]
If you need more than just this, let me know
